// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnpaJCn3C7Lj6f26nyZxCE1EmzpVIkRYw',
    appId: '1:1058350892241:web:29084d22a0c557a15f31f0',
    messagingSenderId: '1058350892241',
    projectId: 'aidigitaltwin-907df',
    authDomain: 'aidigitaltwin-907df.firebaseapp.com',
    storageBucket: 'aidigitaltwin-907df.firebasestorage.app',
    measurementId: 'G-7ZH8BH12S2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3f0rFSTGQVSSKYEb96Q1h2vn9pl5PjfM',
    appId: '1:1058350892241:android:a726f47c838b78485f31f0',
    messagingSenderId: '1058350892241',
    projectId: 'aidigitaltwin-907df',
    storageBucket: 'aidigitaltwin-907df.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDejUIGIx_3P7tNUmSULEK7ShNDJngh0WU',
    appId: '1:1058350892241:ios:c2b7bcc609fe52825f31f0',
    messagingSenderId: '1058350892241',
    projectId: 'aidigitaltwin-907df',
    storageBucket: 'aidigitaltwin-907df.firebasestorage.app',
    iosBundleId: 'com.example.avatarApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDejUIGIx_3P7tNUmSULEK7ShNDJngh0WU',
    appId: '1:1058350892241:ios:c2b7bcc609fe52825f31f0',
    messagingSenderId: '1058350892241',
    projectId: 'aidigitaltwin-907df',
    storageBucket: 'aidigitaltwin-907df.firebasestorage.app',
    iosBundleId: 'com.example.avatarApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnpaJCn3C7Lj6f26nyZxCE1EmzpVIkRYw',
    appId: '1:1058350892241:web:5199042bfa12fbf75f31f0',
    messagingSenderId: '1058350892241',
    projectId: 'aidigitaltwin-907df',
    authDomain: 'aidigitaltwin-907df.firebaseapp.com',
    storageBucket: 'aidigitaltwin-907df.firebasestorage.app',
    measurementId: 'G-BR30F53SB8',
  );
}
